dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python:
  - "2.7"
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=51
    - python: "2.7"
      env: PLONE_VERSION=52
    - python: "3.7"
      env: PLONE_VERSION=52
  sudo: true
  fast_finish: true

before_install:
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt -c constraints_plone$PLONE_VERSION.txt
  - cp test_plone$PLONE_VERSION.cfg buildout.cfg

install:
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True

script:
  - bin/code-analysis
  - bin/test --all

after_success:
  - bin/createcoverage --output-dir=parts/test/coverage
  - bin/pip install coverage
  - bin/python -m coverage.pickle2json
  - bin/pip install -q coveralls
  - bin/coveralls
